import { chromium } from '@playwright/test';
const WEB='http://localhost:5173', API='http://localhost:5080';
const tok = async r => (await (await fetch(`${API}/api/v1/auth/demo-login?role=${r}`)).json()).accessToken;
await fetch(`${API}/api/v1/demo/reset`,{method:'POST',headers:{Authorization:`Bearer ${await tok('DemoPresenter')}`}});
const b = await chromium.launch(); const page = await (await b.newContext({viewport:{width:1600,height:1000},locale:'pl-PL'})).newPage();
page.on('response', async res => { if (res.url().includes('/block')) console.log('RES', res.status()); });
await page.goto(WEB+'/trace/lots/HTS-22-2608',{waitUntil:'domcontentloaded'}); await page.waitForTimeout(1500);
await page.getByTestId('btn-block-lot').first().click(); await page.waitForTimeout(700);
await page.getByLabel(/POWÓD BLOKADY/i).fill('Niezgodność wymiarowa wykryta przy odbiorze');;
await page.getByLabel(/TYTUŁ NCR/i).fill('NCR-QA-001');;
await page.getByRole('button',{name:/Zablokuj partię/}).last().click();
await page.waitForTimeout(2500);
const q = await tok('QualityInspector');
const p = await (await fetch(`${API}/api/v1/passports/PMV-2026-0007`,{headers:{Authorization:`Bearer ${q}`}})).json();
console.log('paszport PMV-2026-0007:', p.status);
const fwd = await (await fetch(`${API}/api/v1/trace/lots/HTS-22-2608/forward`,{headers:{Authorization:`Bearer ${q}`}})).json();
console.log('dotknięte zlecenia:', (fwd.orders||[]).map(o=>o.orderCode||o.code).join(', '));
console.log('dotknięte paszporty:', (fwd.passports||[]).map(x=>`${x.serial}:${x.status}`).join(', '));
await page.goto(WEB+'/passports/PMV-2026-0007',{waitUntil:'domcontentloaded'}); await page.waitForTimeout(1400);
console.log('UI pokazuje unieważnienie:', /Uniewa/i.test(await page.locator('body').innerText()));
await b.close();
