export const keys = {
  me: ['auth', 'me'] as const,
  demoStatus: ['demo', 'status'] as const,
  demoScript: ['demo', 'script'] as const,
  demoAccounts: ['demo', 'accounts'] as const,
  health: ['health'] as const,
  sites: ['sites'] as const,
  // Site-scoped keys carry the active plant as their last segment, so invalidating by the
  // bare prefix (e.g. `keys.dashboard.all`) still clears every plant's cached copy.
  dashboard: {
    all: ['dashboard'] as const,
    kpis: (site: string) => ['dashboard', 'kpis', site] as const,
    map: (site: string) => ['dashboard', 'map', site] as const,
    heatmap: (site: string) => ['dashboard', 'heatmap', site] as const,
    quality: (site: string) => ['dashboard', 'quality', site] as const,
    plan: (site: string) => ['dashboard', 'plan', site] as const,
  },
  suppliers: ['suppliers'] as const,
  purchaseOrders: {
    all: ['purchase-orders'] as const,
    list: (filters: object) => ['purchase-orders', 'list', filters] as const,
    detail: (code: string) => ['purchase-orders', 'detail', code] as const,
    impact: (code: string, lineId: string) => ['purchase-orders', 'impact', code, lineId] as const,
  },
  shipments: {
    all: ['shipments'] as const,
    list: (site: string) => ['shipments', 'list', site] as const,
    detail: (code: string) => ['shipments', 'detail', code] as const,
  },
  logisticsEvents: ['logistics-events'] as const,
  logisticsEventList: (site: string) => ['logistics-events', site] as const,
  documents: (q: Record<string, unknown>) => ['documents', q] as const,
  notifications: ['notifications'] as const,
  planning: {
    all: ['planning'] as const,
    baseline: (site: string) => ['planning', 'baseline', site] as const,
    presets: (site: string) => ['planning', 'presets', site] as const,
    scenarios: (site: string) => ['planning', 'scenarios', 'list', site] as const,
    scenario: (id: string) => ['planning', 'scenarios', id] as const,
    compare: (id: string) => ['planning', 'scenarios', id, 'compare'] as const,
  },
  lots: ['lots'] as const,
  lot: (lotNumber: string) => ['lots', 'detail', lotNumber] as const,
  lotForward: (lotNumber: string) => ['lots', 'forward', lotNumber] as const,
  lotList: (filters: object) => ['lots', 'list', filters] as const,
  trace: {
    search: (q: string, site: string) => ['trace', 'search', q, site] as const,
    serial: (serial: string) => ['trace', 'serial', serial] as const,
    audit: (filters: object) => ['trace', 'audit', filters] as const,
  },
  passports: ['passports'] as const,
  passportList: (filters: object) => ['passports', 'list', filters] as const,
  passport: (serial: string) => ['passports', 'detail', serial] as const,
  quality: ['quality'] as const,
  audit: (filters: object) => ['audit', filters] as const,
  admin: { status: ['admin', 'status'] as const, settings: ['admin', 'settings'] as const },
};
