export const keys = {
  me: ['auth', 'me'] as const,
  demoStatus: ['demo', 'status'] as const,
  demoScript: ['demo', 'script'] as const,
  demoAccounts: ['demo', 'accounts'] as const,
  health: ['health'] as const,
  dashboard: {
    all: ['dashboard'] as const,
    kpis: ['dashboard', 'kpis'] as const,
    map: ['dashboard', 'map'] as const,
    heatmap: ['dashboard', 'heatmap'] as const,
    quality: ['dashboard', 'quality'] as const,
    plan: ['dashboard', 'plan'] as const,
  },
  suppliers: ['suppliers'] as const,
  purchaseOrders: {
    all: ['purchase-orders'] as const,
    list: (filters: Record<string, unknown>) => ['purchase-orders', 'list', filters] as const,
    detail: (code: string) => ['purchase-orders', 'detail', code] as const,
    impact: (code: string, lineId: string) => ['purchase-orders', 'impact', code, lineId] as const,
  },
  shipments: {
    all: ['shipments'] as const,
    detail: (code: string) => ['shipments', 'detail', code] as const,
  },
  logisticsEvents: ['logistics-events'] as const,
  documents: (q: Record<string, unknown>) => ['documents', q] as const,
  notifications: ['notifications'] as const,
  planning: {
    all: ['planning'] as const,
    baseline: ['planning', 'baseline'] as const,
    scenarios: ['planning', 'scenarios'] as const,
    scenario: (id: string) => ['planning', 'scenarios', id] as const,
  },
  lots: ['lots'] as const,
  passports: ['passports'] as const,
  quality: ['quality'] as const,
  admin: { status: ['admin', 'status'] as const, settings: ['admin', 'settings'] as const },
};
